<?php

namespace App\Http\Controllers\Trade;

use App\Domain\Billing\TradeDocuments;
use App\Domain\Documents\DocumentRenders;
use App\Http\Controllers\Controller;
use App\Http\Requests\Trade\CursorRequest;
use App\Http\Support\DocumentDownload;
use App\Http\Support\KeysetCursor;
use App\Http\Support\TradeContext;
use App\Models\AccountStatement;
use App\Support\DisplayTime;
use Carbon\CarbonImmutable;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;
use Inertia\Inertia;
use Inertia\Response;
use Symfony\Component\HttpFoundation\Response as SymfonyResponse;

/**
 * 05.17 §4 — statements: the request form (generated by POST
 * /api/v1/trade/statements), earlier statements, one statement's fixed
 * figures and its PDF. Owners and approvers.
 */
class StatementsPageController extends Controller
{
    private const LIST = 'trade.statements';

    public function __construct(
        private readonly TradeDocuments $documents,
        private readonly DocumentRenders $renders,
    ) {}

    public function index(CursorRequest $request): Response
    {
        [$user, $company] = TradeContext::resolve($request);
        Gate::authorize('viewFinancialDocuments', $company);

        $after = KeysetCursor::decode($request->cursor(), self::LIST, $user->id, $company->id, []);
        $page = $this->documents->statements($company->id, $after);
        $today = CarbonImmutable::now(DisplayTime::zone());

        return Inertia::render('Trade/Statements/Index', [
            'company' => TradeContext::companyProps($company),
            // Default range: the current month to today (05.17 §2).
            'defaults' => ['from_on' => $today->startOfMonth()->toDateString(), 'to_on' => $today->toDateString()],
            'max_months' => (int) config('documents.statement_max_months'),
            'rows' => Inertia::merge($page['rows']),
            'next_cursor' => $page['next'] === null ? null : KeysetCursor::encode(self::LIST, $user->id, $company->id, [], $page['next']),
        ]);
    }

    public function show(Request $request, string $statement): Response
    {
        return Inertia::render('Trade/Statements/Show', ['statement' => $this->documents->statementDetail($this->resolve($request, $statement))]);
    }

    public function download(Request $request, string $statement): SymfonyResponse
    {
        $record = $this->resolve($request, $statement);

        return DocumentDownload::respond($this->renders->readyAttachment('statement', $record->id), route('trade.statements.show', $record->public_id));
    }

    private function resolve(Request $request, string $publicId): AccountStatement
    {
        [, $company] = TradeContext::resolve($request);
        Gate::authorize('viewFinancialDocuments', $company);

        return AccountStatement::query()->with('requestedBy:id,first_name,last_name')->where('public_id', $publicId)->where('company_id', $company->id)->firstOrFail();
    }
}
